name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  gcc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Configure with CMake
      run: cmake -DBUILD_TEST:bool=ON -S . -B build_cmake
    - name: Build (CMake)
      run: cmake --build build_cmake
    - name: Run tests (CMake)
      run: cd build_cmake && ctest && cd ..

  clang:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Configure with CMake
      run: cmake -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang -DBUILD_TEST:bool=ON -S . -B build_cmake
    - name: Build (CMake)
      run: cmake --build build_cmake
    - name: Run tests (CMake)
      run: cd build_cmake && ctest && cd ..
